spring.application.name=Asset Integration Service
assets.login.url=https://assets.nectarit.com/api/towa-integration/1.0.0/token/login
assets.asset.url=https://assets.nectarit.com:8280/alpine-asset-v2/2.0.0/latest/filter/access
assets.login.username=support@buildingdemo
assets.login.password=Pilot@2023
assets.path.uuid=de25c411-6744-497c-97e2-5f7dc6e6a784
assets.building.name=Park Heights
assets.other.api.url=http://localhost:8080/asset-details
server.port=8081